[package]
name = "rust_learn"
version = "0.1.0"
authors = ["Pradipta Bora <190050089@iitb.ac.in>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
